; KV4P-HT ESP32-WROOM fixed-pattern FreeDV 2400B transmitter.

[platformio]
src_dir = .

[env:esp32dev]
platform = platformio/espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../../..
lib_deps =
	https://github.com/pschatzmann/arduino-audio-tools.git#v1.2.3
	https://github.com/fatpat/arduino-dra818.git#89582e3ef7bf3f31f1af149e32cec16c4b9e4cf2
