[platformio]
src_dir = examples/basic

[env:native]
platform = native
test_framework = unity
test_filter = test_native
build_flags =
  -std=gnu++11
  -I src

[env:esp32dev]
platform = platformio/espressif32@6.12.0
board = esp32dev
framework = arduino
test_framework = unity
test_filter = test_esp32
build_flags = -I src

[env:esp32s3]
platform = platformio/espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
test_framework = unity
test_filter = test_esp32
build_flags = -I src

[env:esp32c3]
platform = platformio/espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = arduino
test_framework = unity
test_filter = test_esp32
build_flags = -I src
