[platformio]
src_dir = .

[env]
platform = platformio/espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:request_48000]
build_flags = -DADC_REQUEST_SAMPLE_RATE=48000

[env:request_48400]
build_flags = -DADC_REQUEST_SAMPLE_RATE=48400

[env:request_48188]
build_flags = -DADC_REQUEST_SAMPLE_RATE=48188

[env:request_48190]
build_flags = -DADC_REQUEST_SAMPLE_RATE=48190
