[platformio]
src_dir = .

[env:esp32dev]
platform = platformio/espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 921600
lib_deps =
	https://github.com/pschatzmann/arduino-audio-tools.git#v1.2.3
	https://github.com/fatpat/arduino-dra818.git#89582e3ef7bf3f31f1af149e32cec16c4b9e4cf2

[env:injected_tone]
extends = env:esp32dev
build_flags = -DINJECT_1200HZ_TONE=1

[env:injected_tone_no_apll]
extends = env:esp32dev
build_flags =
	-DINJECT_1200HZ_TONE=1
	-DADC_USE_APLL=0
